### ISSUE TITLE
Schema evolution 

### ISSUE THREAD

**Issue by sksamuel** [51zero/eel-sdk#215]
Should be an easy way to evolve a source given a new schema.

**Comment by hannesmiller** [comment]
Schema Evolution 

- Do we want to follow the same approach that is taken for AVRO schemas?  That is if you add a field:
1. It must be added to the end - I think?
2. It must be optional - nullable=true
3. You must provide a default value - this could be Null
4. For all Sink types and Hive dialects ensure it's schema evolution capable - should throw a Runtime exception if not capable

- I had a bad experience once where we auto-generated AVRO schemas for Parquet Hive tables - we always put meta data columns at the front which was capable of reading old and new data via the Parquet API, however Hive doesn't like this because Hive by default maps columns by its index or ordinal - note I just found out that you can change this by mapping it by name, here's an excerpt from stack overflow:

http://stackoverflow.com/questions/37644664/schema-evolution-in-parquet-format

Without schema evolution you can read schema from one parquet file, and while reading rest of files assume it stays the same.
Parquet schema evolution is implementation-dependent.
Hive for example has a knob 
*parquet.column.index.access=false* that you could set to map schema by column names rather than by column index. Then you could *delete* columns too, not just add.

- You could a runtime for the above for Hive Parquet dialect - note I have never tried this before

**Comment by hannesmiller** [comment]
*Tool*

In addition you could write a tool that looks at all the files (Parquet) and produces a new schema by merging all the Schemas into one

- This would be very useful for Hive, i.e.  generate alter table add column DDL statements

**Comment by sksamuel** [comment]
So things to do for this:

* parquet source must read schemas from all files and merge to form the final schema
* orc source must do the same
* all hive files for a table must conform to the schema in the hive metastore, if that contains extra fields, then the rows must be padded to match

**Comment by sksamuel** [comment]
Done.
