### ISSUE TITLE
Use OrcStruct API in ORC 1.1.0 which doesn't require Hive exec jars and all its dependencies 

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#246]
We should consider using the **OrcStruct** API for Orc which appears to isolate you from a specific version of Hadoop/Hive and doesn't require Hive Exec and all its dependencies, i.e. here's an excerpt from the Orc [Documentation](http://orc.apache.org/docs/adopters.html) ...

ORC files have always supporting reading and writing from Hadoop’s MapReduce, but with the ORC 1.1.0 release it is now easier than ever without pulling in Hive’s exec jar and all of its dependencies. OrcStruct now also implements WritableComparable and can be serialized through the MapReduce shuffle.

**Comment by sksamuel** [comment]
I thought that's what we already used.

On 14 Feb 2017 9:16 a.m., "hannesmiller" <notifications@github.com> wrote:

We should consider using the following API for Orc which appears to isolate
you from specific version of Hadoop, i.e. here's an excerpt from the Orc
Documentation <http://orc.apache.org/docs/adopters.html> ...

ORC files have always supporting reading and writing from Hadoop’s
MapReduce, but with the ORC 1.1.0 release it is now easier than ever
without pulling in Hive’s exec jar and all of its dependencies. OrcStruct
now also implements WritableComparable and can be serialized through the
MapReduce shuffle.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sksamuel/eel-sdk/issues/246>, or mute the thread
