### ISSUE TITLE
Coercing from a Decimal to a Double is currently not supported

### ISSUE THREAD

**Issue by hannesmiller** [51zero/eel-sdk#260]
I am using the following code on the Frame to replace Decimal with Double which yields an exception:
```scala
.toFrame(new MyListener())
.replaceFieldType(DecimalType(38, 5), DoubleType)
```

- I think the following Coercer should change from:
```scala
object DoubleCoercer extends Coercer[Double] {
  override def coerce(input: Any): Double = input match {
    case b: Byte => b
    case d: Double => d
    case f: Float => f
    case i: Int => i
    case l: Long => l
    case s: Short => s
    case s: String => s.toDouble
  }
}
```
-  to:
```scala
  object DoubleCoercer extends Coercer[Double] {
    override def coerce(input: Any): Double = input match {
      case d: Double => d
      case f: Float => f
      case bd: BigDecimal => bd.toDouble
      case bd: java.math.BigDecimal => bd.doubleValue
      case b: Byte => b
      case i: Int => i
      case l: Long => l
      case s: Short => s
      case s: String => s.toDouble
    }
  }
```

**Comment by sksamuel** [comment]
We've discussed this before. This would be a lossy conversion so do we want
to silently lose precision. Personally I don't think we should.

On 28 Feb 2017 12:41 p.m., "hannesmiller" <notifications@github.com> wrote:

I am using the following code on the Frame to replace Decimal with Double
which yields an exception:

.toFrame(new MyListener())
.replaceFieldType(DecimalType(38, 5), DoubleType)


   - I think the following Coercer should change from:

object DoubleCoercer extends Coercer[Double] {
  override def coerce(input: Any): Double = input match {
    case b: Byte => b
    case d: Double => d
    case f: Float => f
    case i: Int => i
    case l: Long => l
    case s: Short => s
    case s: String => s.toDouble
  }
}


   - to:

  object DoubleCoercer extends Coercer[Double] {
    override def coerce(input: Any): Double = input match {
      case bd: BigDecimal => bd.toDouble
      case bd: java.math.BigDecimal => bd.doubleValue
      case b: Byte => b
      case d: Double => d
      case f: Float => f
      case i: Int => i
      case l: Long => l
      case s: Short => s
      case s: String => s.toDouble
    }
  }

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sksamuel/eel-sdk/issues/260>, or mute the thread

**Comment by hannesmiller** [comment]
You could then say the same about the other types such as **int, float, long, short**

**Comment by hannesmiller** [comment]
In this case I want to take the hit on loss because HBase doesn't support Decimals correctly.

**Comment by sksamuel** [comment]
Yep we only make a non lossy conversion don't we.

**Comment by sksamuel** [comment]
I'm closing this as I don't think Doubles should be silently converted to Decimals. We can add mechanism to allow the user to force it explicitly.

**Comment by hannesmiller** [comment]
Ok but you could make the same argument for other intrinsic types like float?

**Comment by sksamuel** [comment]
yes we don't do any lossy conversions at all.
